<?php
/**
 * Copyright © Nimasystems (info@nimasystems.com). All rights reserved.
 * Please visit Nimasystems.com for license details
 */
/**
 * @var \Nimasystems\AddMultipleProducts\Block\Product\Action $block
 */
?>

<div style="display:none !important;" class="qty-controller" data-addmultipleproducts-js="qtycontroller-<?= /* @noEscape */$block->getProductId() ?>"></div>

<script type="text/x-magento-init">
    {
        "[data-addmultipleproducts-js='qtycontroller-<?= /* @noEscape */$block->getProductId() ?>']": {
            "Nimasystems_AddMultipleProducts/js/view/product/qty_controller": {
                "productId": <?= /* @noEscape */$block->getProductId() ?>,
                "addUrl": "<?= /* @noEscape */$block->getAddUrl() ?>",
                "valueFormatString": <?= /* @noEscape */json_encode($block->getValueFormatString()) ?>,
                "plSelector": <?= /* @noEscape */json_encode($block->getProductListViewJqueryContainerSelector()) ?>,
                "pvSelector": <?= /* @noEscape */json_encode($block->getProductViewJqueryContainerSelector()) ?>,
                "stockConfig": <?= /* @noEscape */json_encode($block->getStockConfig()) ?>
            }
        }
    }
</script>
