<?php
/**
 * Copyright © Nimasystems (info@nimasystems.com). All rights reserved.
 * Please visit Nimasystems.com for license details
 */
/**
 * @var \Nimasystems\AddMultipleProducts\Block\Product\Action $block
 */
?>

<div style="display:none" class="qty-controller" data-addmultipleproducts-js="qtycontroller-<?= /* @noEscape */$block->getProductId() ?>">
    <button class="qty-dec" type="button" title="<?= __('Decrease Quantity') ?>"></button>
    <div class="quantity-value">
        <span class="value">
            <span title="<?= __('Click to edit') ?>" class="qty-view">
                <span aria-label="<?= __('Current Quantity') ?>" class="item-qty"></span>
            </span>
            <input style="display: none;" type="text" class="qty-input" value="1" />
        </span>
    </div>
    <button class="qty-inc" type="button" title="<?= __('Increase Quantity') ?>"></button>
</div>

<script type="text/x-magento-init">
    {
        "[data-addmultipleproducts-js='qtycontroller-<?= /* @noEscape */$block->getProductId() ?>']": {
            "Nimasystems_AddMultipleProducts/js/view/product/qty_controller": {
                "productId": <?= /* @noEscape */$block->getProductId() ?>,
                "addUrl": "<?= /* @noEscape */$block->getAddUrl() ?>",
                "valueFormatString": <?= /* @noEscape */json_encode($block->getValueFormatString()) ?>,
                "maxQty": <?= /* @noEscape */json_encode($block->getMaximumQuantity()) ?>,
                "initialQty": <?= /* @noEscape */$block->getProductCartQty() ?>
            }
        }
    }
</script>
